import { NextResponse, type NextRequest } from "next/server";
import { RESERVED_SLUGS } from "@/modules/share/domain/slug";

const SESSION_COOKIE_NAMES = ["authjs.session-token", "__Secure-authjs.session-token"];

/**
 * Top-level static asset filename. Anything in `public/` served at `/<name>.<ext>`
 * with a safe asset extension is public — no auth gate.
 *
 * THIS PATTERN IS THE SOURCE OF TRUTH. New files dropped into `public/` (or
 * generated by Next's metadata routes at /<name>.<ext>) are auto-allowlisted
 * by extension. You should never have to add explicit names here again. See
 * AGENTS.md → "Public static assets" for the rule.
 */
const PUBLIC_STATIC_RE = /^\/[a-z0-9._-]+\.(svg|png|jpg|jpeg|gif|ico|webp|avif|webmanifest|xml|txt|json|js|map)$/i;

function hasSessionCookie(req: NextRequest): boolean {
  return SESSION_COOKIE_NAMES.some((name) => req.cookies.has(name));
}

/**
 * Dev-only auth bypass — mirrors `maybeDevBypass()` in
 * `modules/auth/presentation/session.ts`. Triple-gated:
 *   1. NODE_ENV === "development"
 *   2. DEV_BYPASS_AUTH === "1"
 *   3. Request host is loopback / RFC1918 private
 * Skips the proxy's optimistic auth redirect when active so the local dev
 * machine never has to round-trip through GitHub OAuth.
 */
function isLocalDevBypass(req: NextRequest): boolean {
  if (process.env["NODE_ENV"] !== "development") return false;
  if (process.env["DEV_BYPASS_AUTH"] !== "1") return false;
  const host = (req.headers.get("host") ?? "").toLowerCase().split(":")[0] ?? "";
  if (host === "localhost" || host === "127.0.0.1" || host === "::1") return true;
  if (host.startsWith("192.168.") || host.startsWith("10.")) return true;
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(host)) return true;
  return false;
}

/**
 * Matches `/<slug>` where slug is one URL segment that:
 *   • starts with a lowercase letter or digit,
 *   • contains only `[a-z0-9-]`, no leading/trailing/double hyphen,
 *   • is NOT in RESERVED_SLUGS (which also covers every internal
 *     route prefix the app owns).
 *
 * Sourcing the reserved set from the slug domain (the same one the
 * validator uses) means there's exactly one list to maintain.
 */
const SLUG_PATTERN = /^\/([a-z0-9]+(?:-[a-z0-9]+)*)$/;
export function isPublicSlugPath(pathname: string): boolean {
  const m = SLUG_PATTERN.exec(pathname);
  if (!m) return false;
  const first = m[1];
  if (first === undefined) return false;
  return !RESERVED_SLUGS.has(first);
}

export function isPublicPath(pathname: string): boolean {
  return (
    // Home page IS the login screen when unauth — `(vault)/layout.tsx`
    // short-circuits to <LoginScreen /> instead of redirecting. Marking
    // `/` public here stops the proxy from 307-ing to `/login` first
    // and lets the layout own the auth-state decision.
    pathname === "/" ||
    pathname === "/login" ||
    // Legal and commercial pages a stranger must be able to read before signing in.
    // Placeholders until the texts are written (plan v5, the legal section).
    pathname === "/privacy" ||
    pathname === "/terms" ||
    pathname === "/pricing" ||
    pathname === "/refunds" ||
    // Public shared notes:
    //   • Modern URL: /<slug>   (one segment, reserved-list filtered).
    //   • Legacy URL: /p/<slug> (301 redirected by the handler — kept
    //     public so the redirect itself doesn't bounce through /login).
    isPublicSlugPath(pathname) ||
    pathname.startsWith("/p/") ||
    pathname.startsWith("/api/auth") ||
    pathname.startsWith("/_next/static") ||
    pathname.startsWith("/_next/image") ||
    // Any top-level static asset by extension (favicons, OG images, brand SVGs,
    // PWA manifest, service worker, sitemap, robots, theme-init, etc.).
    PUBLIC_STATIC_RE.test(pathname) ||
    // Static directories served straight out of public/. Their assets are NESTED
    // paths (/decisions/app.css), and PUBLIC_STATIC_RE only matches a single
    // top-level segment with one of fourteen extensions — neither .css nor .html
    // is in that list — so every one of them 307s to /login without this.
    // Both names are in RESERVED_SLUGS so a note cannot shadow them.
    pathname === "/decisions" ||
    pathname.startsWith("/decisions/") ||
    pathname === "/prototype" ||
    pathname.startsWith("/prototype/") ||
    // Next metadata routes that don't end in a static extension yet still need
    // to be public for crawlers / image consumers.
    pathname === "/opengraph-image" ||
    pathname.startsWith("/opengraph-image.")
  );
}

export function proxy(req: NextRequest) {
  const { pathname } = req.nextUrl;

  // Optimistic auth redirect for PAGE navigations only — real guard is
  // (vault)/layout.tsx. API routes self-gate and return JSON 401, so never
  // redirect them (a redirect would hand a fetch() HTML instead of an error).
  if (
    !hasSessionCookie(req) &&
    !isPublicPath(pathname) &&
    !pathname.startsWith("/api/") &&
    !isLocalDevBypass(req)
  ) {
    return NextResponse.redirect(new URL("/login", req.url));
  }

  const res = NextResponse.next();
  // nosniff / X-Frame-Options / Referrer-Policy are set globally in
  // next.config.ts headers() (covers static assets too). Here we only add the
  // CSP for dynamic routes.
  // CSP — Report-Only for the authed editor (single trusted tenant). The public
  // /p/* renderer gets an ENFORCED tight CSP via next.config.ts headers().
  // Allows: self, blob/data URIs (CodeMirror + mermaid SVG), GitHub avatars,
  // KaTeX CDN font fallback, mermaid CDN script (used by /api/export/pdf
  // and the preview pane), and the Vercel AI Gateway. inline scripts/styles
  // are allowed for now (Tailwind injects, mermaid sets style attrs).
  res.headers.set(
    "Content-Security-Policy-Report-Only",
    [
      "default-src 'self'",
      "img-src 'self' data: blob: https://avatars.githubusercontent.com",
      // mermaid + KaTeX are bundled (not CDN); only inline/eval needed.
      "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
      "style-src 'self' 'unsafe-inline'",
      "font-src 'self' data:",
      "connect-src 'self' https://api.github.com https://ai-gateway.vercel.sh",
      // Media + iframe embeds (YouTube/Vimeo/PDF). Without these the embeds
      // break the moment CSP is enforced (currently report-only).
      "media-src 'self' blob: https:",
      "frame-src 'self' blob: https://www.youtube-nocookie.com https://player.vimeo.com",
      "worker-src 'self' blob:",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self' https://github.com",
      "object-src 'none'",
    ].join("; "),
  );
  return res;
}

export const config = {
  // Skip the middleware entirely for top-level static assets so the proxy
  // never runs on them. Mirrors PUBLIC_STATIC_RE above — keep in sync.
  matcher: [
    "/((?!_next/static|_next/image|[^/]+\\.(?:svg|png|jpg|jpeg|gif|ico|webp|avif|webmanifest|xml|txt|json|js|map)$).*)",
  ],
};
