#!/usr/bin/env python3
"""Fill the generated index block inside 00-README.md.

    python3 docs/pack/tools/gen-index.py

The README routes by task, which is what a person wants. But a task router does not list
everything, and a file nobody routes to is a file nobody reads. This writes a complete
table between the INDEX markers, from each file's own front matter, so it cannot drift.

The block is marked generated in the README itself. Everything outside the markers is
hand-written and is never touched.
"""
import pathlib
import re
import sys

PACK = pathlib.Path(__file__).resolve().parent.parent
README = PACK / '00-README.md'
START, END = '<!-- INDEX:START -->', '<!-- INDEX:END -->'

BANDS = [
    (0, 9, 'Orient'), (10, 19, 'Specify'), (20, 29, 'Engineer'),
    (30, 39, 'Run'), (40, 49, 'Judge'), (50, 59, 'Steer'), (60, 69, 'Trace and meta'),
]


def meta(p):
    t = p.read_text(encoding='utf-8')
    out = {}
    if t.startswith('---\n'):
        end = t.find('\n---', 4)
        for line in t[4:end].split('\n'):
            if ':' in line and not line.startswith(' '):
                k, _, v = line.partition(':')
                out[k.strip()] = v.strip().strip('"').strip("'")
    return out


rows = []
for f in sorted(PACK.glob('*.md')):
    if not f.stem[:2].isdigit():
        continue
    m = meta(f)
    rows.append((int(f.stem[:2]), f.name, m.get('title', f.stem), m.get('mode', '?'),
                 m.get('tier', '?'), m.get('status', '?')))

screens = sorted((PACK / '12-screens').glob('S*.md'))

lines = ['', '**Generated by `tools/gen-index.py`. Do not edit between the markers.**', '']
for lo, hi, band in BANDS:
    band_rows = [r for r in rows if lo <= r[0] <= hi]
    if not band_rows:
        continue
    lines += [f'### {lo:02d} to {hi:02d}. {band}', '', 'File | What it is | Mode | Tier | Status']
    for _, name, title, mode, tier, status in band_rows:
        # A full stop after the title: without one the writing gate reads a whole band's table as one
        # sentence of 120 words and blocks the README.
        lines.append(f'[{name}]({name}) | {title.rstrip(".")}. | {mode} | {tier} | {status}')
    if lo == 10 and screens:
        first, last = screens[0].stem, screens[-1].stem
        lines.append(f'[12-screens/]({"12-screens/" + screens[0].name}) | '
                     f'One specification per screen, {first} to {last}, {len(screens)} files. | '
                     f'reference | canonical | specified')
    lines.append('')

adrs = sorted((PACK / 'adr').glob('ADR-*.md'))
if adrs:
    lines += ['### Decision records', '', 'File | What it is | Mode | Tier | Status']
    for f in adrs:
        m = meta(f)
        lines.append(f'[adr/{f.name}](adr/{f.name}) | {m.get("title", f.stem).rstrip(".")}. | '
                     f'{m.get("mode", "?")} | {m.get("tier", "?")} | {m.get("status", "?")}')
    lines.append('')

block = '\n'.join(lines)
t = README.read_text(encoding='utf-8')
if START not in t:
    anchor = '## Routing, by what you are trying to do'
    t = t.replace(anchor, f'## Every file\n\n{START}\n{END}\n\n{anchor}', 1)
t = re.sub(re.escape(START) + r'.*?' + re.escape(END), START + '\n' + block + END, t, flags=re.S)
README.write_text(t, encoding='utf-8')
print(f'index written: {len(rows)} numbered files, {len(screens)} screens')
